# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master       

    - name: Install system dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
   
                
    - name: Install R package dependencies
      run: |
        if (!require('remotes')) install.packages('remotes')
        if (!require('rvest')) remotes::install_github('tidyverse/rvest')
      shell: Rscript {0}
   
    - name: Fetch stats and update README.md
      run: |
        Rscript scrape_google_scholar.R
    
    - name: Commit and push if needed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated README.md automatically" || exit 0
        git push
